In [ ]:
Scrapping 
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India
OBJECTIVES
Request webpage	
Check request worked	
Parse HTML with BeautifulSoup	
Identify repeated container (tr)	
Extract titles/language names	
Extract relevant data	
Extract links	
Create DataFrame	
Inspect DataFrame	
Clean scraped data	
Save to CSV

import pandas as pd

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

response = requests.get(url, headers=headers, timeout=20)

print(response.status_code)
print(response.url)

200
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India

In [6]:
soup = BeautifulSoup(response.text, "html.parser")

In [7]:
print(soup.title.text)

List of languages by number of native speakers in India - Wikipedia

In [8]:
title = soup.title.text.replace(" - Wikipedia", "")
print(title)

List of languages by number of native speakers in India

In [9]:
tables = soup.find_all("table")

print(len(tables))

13

In [10]:
for i, table in enumerate(tables):
    print("TABLE", i)
    print(table.get_text(" ", strip=True)[:300])
    print("-" * 50)

TABLE 0
First, second, and third languages by number of speakers in India (2011 Census) First language speakers Second language speakers [ 14 ] Third language speakers [ 14 ] Total speakers Language Figure [ 14 ] % of total population Figure [ 15 ] [ 14 ] % of total population Hindi [ note 2 ] 528,347,193 4
--------------------------------------------------
TABLE 1
Table: Population ordered by number of native speakers Rank Language 1991 census of India [ 16 ] (total: 838,583,988) 2001 census of India [ 17 ] (total: 1,028,610,328) 2011 Census of India [ 18 ] [ 19 ] (total: 1,210,854,977) [ 20 ] Encarta 2007 estimate [ 21 ] Worldwide total Speakers Percentage S
--------------------------------------------------
TABLE 2
Rank Language 2001 census Speakers Percentage 32 Kui 916,222 0.089% 33 Lushai/Mizo 674,756 0.066% 34 Halabi 593,443 0.058% 35 Korku 574,481 0.056% 36 Miri/Mishing 551,224 0.054% 37 Munda 469,357 0.046% 38 Karbi/Mikir 419,534 0.041% 39 Koya 362,070 0.035% 40 Ao 261,387 0.025% 41 Savara 252,519 0.025%
--------------------------------------------------
TABLE 3
Mother tongues with more than one million speakers Rank Mother tongue 2011 census Included in language Speakers Percentage 1 Hindi 322,200,000 26.6 % 2 Bengali 96,180,000 7.94 % 3 Marathi 82,800,000 6.84 % 4 Telugu 80,910,000 6.68 % 5 Tamil 68,890,000 5.69 % 6 Gujarati 55,040,000 4.55 % 7 Urdu 50,73
--------------------------------------------------
TABLE 4
v t e Languages of India Official languages Union-level Hindi English 8th schedule to the Constitution of India Classical Assamese Bengali Kannada Malayalam Marathi Odia Sanskrit Tamil Telugu Non-classical Bodo Dogri Gujarati Hindi Kashmiri Konkani Maithili Meitei (Manipuri) Nepali Punjabi Santali S
--------------------------------------------------
TABLE 5
Union-level Hindi English 8th schedule to the Constitution of India Classical Assamese Bengali Kannada Malayalam Marathi Odia Sanskrit Tamil Telugu Non-classical Bodo Dogri Gujarati Hindi Kashmiri Konkani Maithili Meitei (Manipuri) Nepali Punjabi Santali Sindhi Urdu State-level only Angika Bhojpuri
--------------------------------------------------
TABLE 6
Classical Assamese Bengali Kannada Malayalam Marathi Odia Sanskrit Tamil Telugu Non-classical Bodo Dogri Gujarati Hindi Kashmiri Konkani Maithili Meitei (Manipuri) Nepali Punjabi Santali Sindhi Urdu
--------------------------------------------------
TABLE 7
Over 1 million speakers Awadhi Bagheli Bagri Bajjika Bhili Bundeli Braj Dhundhari Garhwali Gondi Harauti Haryanvi Kangri Khandeshi Kumaoni Lambadi Malvi Marwari Mewari Nimadi Rajasthani Surjapuri Tulu Wagdi Varhadi 100,000 – 1 million speakers Adi Angami Ao Badaga Dimasa Halbi Karbi Khotta Kodava Ko
--------------------------------------------------
TABLE 8
v t e Major languages of South Asia Languages of Afghanistan Bangladesh Bhutan India list by number of speakers scheduled classical Maldives Nepal Pakistan Sri Lanka Contemporary languages Great Andamanese Aka-Jeru Dravidian Brahui Kannada Malayalam Tamil Telugu Tulu Indo-European Germanic English B
--------------------------------------------------
TABLE 9
Great Andamanese Aka-Jeru Dravidian Brahui Kannada Malayalam Tamil Telugu Tulu Indo-European Germanic English Bangladeshi Indian Nepalese Pakistani Sri Lankan Indo-Aryan Angika Assamese Bhojpuri Bengali Chakma Chittagonian Dhivehi Dogri Gujarati Hindustani Hindi Urdu Hinglish Hindko Kashmiri Konkani
--------------------------------------------------
TABLE 10
Germanic English Bangladeshi Indian Nepalese Pakistani Sri Lankan Indo-Aryan Angika Assamese Bhojpuri Bengali Chakma Chittagonian Dhivehi Dogri Gujarati Hindustani Hindi Urdu Hinglish Hindko Kashmiri Konkani Kumaoni Magahi Mahal Maithili Marathi Nepali Odia Punjabi Rajasthani Rangpuri Sanskrit Sarai
--------------------------------------------------
TABLE 11
Khasic Khasi Lyngngam Pnar War Munda Ho Korku Mundari Santali Sora Nicobaric Car Central Nicobarese Chaura Southern Nicobarese Teressa Shompen ?
--------------------------------------------------
TABLE 12
Historical Brahmi (Abugida) Greek Indus (Undeciphered) Kharosthi Arabic Arabi Malayalam Arwi Nastaliq Shahmukhi Brahmic Devanagari Bengali Gujarati Gurmukhi Malayalam Kannada Odia Ranjana Sinhala Tamil Telugu Old Italic Latin Other Thaana
--------------------------------------------------

In [11]:
language_table = tables[1]

In [12]:
rows = language_table.find_all("tr")

for row in rows[:5]:
    print(row.get_text(" | ", strip=True))

Rank | Language | 1991 census of India | [ | 16 | ] | (total: 838,583,988) | 2001 census of India | [ | 17 | ] | (total: 1,028,610,328) | 2011 Census of India | [ | 18 | ] | [ | 19 | ] | (total: 1,210,854,977) | [ | 20 | ] | Encarta | 2007 estimate | [ | 21 | ] | Worldwide total
Speakers | Percentage | Speakers | Percentage | Speakers | Percentage | Speakers
1 | Hindi | [ | note 2 | ] | 329,518,087 | 39.29% | 422,048,642 | 41.1% | 528,347,193 | 43.63% | 366 million
2 | Bengali | 69,595,738 | 8.30% | 83,193,311 | 8.09% | 97,237,669 | 8.03% | 207 million
3 | Marathi | 62,481,681 | 7.45% | 71,936,894 | 6.99% | 83,026,680 | 6.86% | 68.0 million

In [13]:
data = []

for row in rows[1:]:
    cells = row.find_all(["th", "td"])
    cells = [cell.get_text(" ", strip=True) for cell in cells]
    
    if cells:
        data.append(cells)

In [14]:
for row in data[:5]:
    print(row)

['', '', 'Speakers', 'Percentage', 'Speakers', 'Percentage', 'Speakers', 'Percentage', 'Speakers']
['1', 'Hindi [ note 2 ]', '329,518,087', '39.29%', '422,048,642', '41.1%', '528,347,193', '43.63%', '366 million']
['2', 'Bengali', '69,595,738', '8.30%', '83,193,311', '8.09%', '97,237,669', '8.03%', '207 million']
['3', 'Marathi', '62,481,681', '7.45%', '71,936,894', '6.99%', '83,026,680', '6.86%', '68.0 million']
['4', 'Telugu', '66,017,615', '7.87%', '74,002,856', '7.19%', '81,127,740', '6.70%', '69.7 million']

In [15]:
for row in data[:5]:
    print(len(row))

9
9
9
9
9

In [17]:
for row in data[:3]:
    print(row)

['', '', 'Speakers', 'Percentage', 'Speakers', 'Percentage', 'Speakers', 'Percentage', 'Speakers']
['1', 'Hindi [ note 2 ]', '329,518,087', '39.29%', '422,048,642', '41.1%', '528,347,193', '43.63%', '366 million']
['2', 'Bengali', '69,595,738', '8.30%', '83,193,311', '8.09%', '97,237,669', '8.03%', '207 million']

In [19]:
language_data = []

for row in data[1:]:
    language_data.append({
        "rank": row[0],
        "language": row[1],
        "speakers_2011": row[6],
        "percentage_2011": row[7]
    })

language_df = pd.DataFrame(language_data)

In [20]:
language_df.head()

  rank          language speakers_2011 percentage_2011
0    1  Hindi [ note 2 ]   528,347,193          43.63%
1    2           Bengali    97,237,669           8.03%
2    3           Marathi    83,026,680           6.86%
3    4            Telugu    81,127,740           6.70%
4    5             Tamil    69,026,881           5.70%

In [21]:
language_df["language"] = language_df["language"].str.replace(
    r"\[.*?\]",
    "",
    regex=True
).str.strip()

In [22]:
language_df.head()

  rank language speakers_2011 percentage_2011
0    1    Hindi   528,347,193          43.63%
1    2  Bengali    97,237,669           8.03%
2    3  Marathi    83,026,680           6.86%
3    4   Telugu    81,127,740           6.70%
4    5    Tamil    69,026,881           5.70%

In [26]:
language_df = pd.DataFrame(data[1:], columns=[
    "rank",
    "language",
    "speakers_1991",
    "percentage_1991",
    "speakers_2001",
    "percentage_2001",
    "speakers_2011",
    "percentage_2011",
    "worldwide_speakers"
])

In [27]:
language_df.head()

,rank,language,speakers_1991,percentage_1991,speakers_2001,percentage_2001,speakers_2011,percentage_2011,worldwide_speakers
0,1,Hindi [ note 2 ],"329,518,087",39.29%,"422,048,642",41.1%,"528,347,193",43.63%,366 million
1,2,Bengali,"69,595,738",8.30%,"83,193,311",8.09%,"97,237,669",8.03%,207 million
2,3,Marathi,"62,481,681",7.45%,"71,936,894",6.99%,"83,026,680",6.86%,68.0 million
3,4,Telugu,"66,017,615",7.87%,"74,002,856",7.19%,"81,127,740",6.70%,69.7 million
4,5,Tamil,"53,006,368",6.32%,"60,793,814",5.91%,"69,026,881",5.70%,66.0 million

In [29]:
language_df["language"] = (
    language_df["language"]
    .str.replace(r"\[.*?\]", "", regex=True)
    .str.strip()
)

In [31]:
language_df.to_csv("india_languages.csv", index=False)

In [32]:
language_df.head(10)

,rank,language,speakers_1991,percentage_1991,speakers_2001,percentage_2001,speakers_2011,percentage_2011,worldwide_speakers
0,1,Hindi,"329,518,087",39.29%,"422,048,642",41.1%,"528,347,193",43.63%,366 million
1,2,Bengali,"69,595,738",8.30%,"83,193,311",8.09%,"97,237,669",8.03%,207 million
2,3,Marathi,"62,481,681",7.45%,"71,936,894",6.99%,"83,026,680",6.86%,68.0 million
3,4,Telugu,"66,017,615",7.87%,"74,002,856",7.19%,"81,127,740",6.70%,69.7 million
4,5,Tamil,"53,006,368",6.32%,"60,793,814",5.91%,"69,026,881",5.70%,66.0 million
5,6,Gujarati,"40,673,814",4.85%,"46,091,617",4.48%,"55,492,554",4.58%,46.1 million
6,7,Urdu,"43,406,932",5.18%,"51,536,111",5.01%,"50,772,631",4.19%,60.3 million
7,8,Kannada,"32,753,676",3.91%,"37,924,011",3.69%,"43,706,512",3.61%,35.3 million
8,9,Odia,"28,061,313",3.35%,"33,017,446",3.21%,"37,521,324",3.10%,32.3 million
9,10,Malayalam,"30,377,176",3.62%,"33,066,392",3.21%,"34,838,819",2.88%,35.7 million

In [33]:
language_df.shape

(31, 9)

In [34]:
language_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rank                31 non-null     str
 1   language            31 non-null     str
 2   speakers_1991       31 non-null     str
 3   percentage_1991     31 non-null     str
 4   speakers_2001       31 non-null     str
 5   percentage_2001     31 non-null     str
 6   speakers_2011       31 non-null     str
 7   percentage_2011     31 non-null     str
 8   worldwide_speakers  31 non-null     str
dtypes: str(9)
memory usage: 2.3 KB

In [35]:
language_df["language"] = (
    language_df["language"]
    .str.replace(r"\[.*?\]", "", regex=True)
    .str.strip()
)

In [36]:
language_df["language"].head()

0      Hindi
1    Bengali
2    Marathi
3     Telugu
4      Tamil
Name: language, dtype: str

In [56]:
for col in ["percentage_1991", "percentage_2001", "percentage_2011"]:
    language_df[col] = (
        language_df[col]
        .astype(str)
        .str.replace("%", "", regex=False)
        .str.strip()
    )

    language_df[col] = pd.to_numeric(
        language_df[col],
        errors="coerce"
    )

In [57]:
language_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rank                31 non-null     int64
 1   language            31 non-null     str
 2   speakers_1991       31 non-null     str
 3   percentage_1991     19 non-null     float64
 4   speakers_2001       31 non-null     int64
 5   percentage_2001     31 non-null     float64
 6   speakers_2011       31 non-null     int64
 7   percentage_2011     31 non-null     float64
 8   worldwide_speakers  31 non-null     str
dtypes: float64(3), int64(3), str(3)
memory usage: 2.3 KB

In [58]:
language_df.head()

,rank,language,speakers_1991,percentage_1991,speakers_2001,percentage_2001,speakers_2011,percentage_2011,worldwide_speakers
0,1,Hindi,"329,518,087",39.29,422048642,41.10,528347193,43.63,366 million
1,2,Bengali,"69,595,738",8.30,83193311,8.09,97237669,8.03,207 million
2,3,Marathi,"62,481,681",7.45,71936894,6.99,83026680,6.86,68.0 million
3,4,Telugu,"66,017,615",7.87,74002856,7.19,81127740,6.70,69.7 million
4,5,Tamil,"53,006,368",6.32,60793814,5.91,69026881,5.70,66.0 million

In [59]:
links = []

for row in rows[1:]:
    link = row.find("a")

    if link and link.get("href"):
        href = link.get("href")

        if href.startswith("/"):
            links.append("https://en.wikipedia.org" + href)
        else:
            links.append(href)
    else:
        links.append(None)

In [62]:
len(language_df), len(links)

(31, 32)

In [63]:
links = []

for row in rows[2:]:
    link = row.find("a")

    if link and link.get("href"):
        href = link.get("href")

        if href.startswith("/"):
            links.append("https://en.wikipedia.org" + href)
        else:
            links.append(href)
    else:
        links.append(None)

In [64]:
len(links)

31

In [65]:
language_df["link"] = links

In [66]:
language_df[["language", "link"]].head()

  language                                            link
0    Hindi             https://en.wikipedia.org/wiki/Hindi
1  Bengali  https://en.wikipedia.org/wiki/Bengali_language
2  Marathi  https://en.wikipedia.org/wiki/Marathi_language
3   Telugu   https://en.wikipedia.org/wiki/Telugu_language
4    Tamil    https://en.wikipedia.org/wiki/Tamil_language

In [67]:
language_df.to_csv("india_languages.csv", index=False)

In [68]:
import os

print(os.path.exists("india_languages.csv"))

True

In [69]:
language_df.head()

,rank,language,speakers_1991,percentage_1991,speakers_2001,percentage_2001,speakers_2011,percentage_2011,worldwide_speakers,link
0,1,Hindi,"329,518,087",39.29,422048642,41.10,528347193,43.63,366 million,https://en.wikipedia.org/wiki/Hindi
1,2,Bengali,"69,595,738",8.30,83193311,8.09,97237669,8.03,207 million,https://en.wikipedia.org/wiki/Bengali_language
2,3,Marathi,"62,481,681",7.45,71936894,6.99,83026680,6.86,68.0 million,https://en.wikipedia.org/wiki/Marathi_language
3,4,Telugu,"66,017,615",7.87,74002856,7.19,81127740,6.70,69.7 million,https://en.wikipedia.org/wiki/Telugu_language
4,5,Tamil,"53,006,368",6.32,60793814,5.91,69026881,5.70,66.0 million,https://en.wikipedia.org/wiki/Tamil_language

In [70]:
language_df.shape

(31, 10)

language_df.to_csv("india_languages.csv", index=False)